bihealth/snappy-pipeline

- snappy_pipeline/__init__.py
> Add missing imports to fix expand_ref bug

- snappy_pipeline/workflows/abstract/__init__.py
closes #13 
**Summary**
Fixed bug while defining path to sample sheet (e.g., `2021_<project_name>.tsv`) before invalidating cache.
> Fix bug in cache invalidation

- snappy_pipeline/workflows/abstract/__init__.py
Reverts bihealth/snappy-pipeline#34
> Revert "Fix bug in cache invalidation"

- snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py
> Renamed duplicated class in somatic_wgs_sv_calling

- README.rst
- snappy_pipeline/workflows/abstract/__init__.py
- snappy_pipeline/workflows/ngs_mapping/__init__.py
- snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py
- tests/snappy_pipeline/workflows/conftest.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping.py
- tests/snappy_wrappers/wrappers/test_wrappers.py
closes #49 
**Changes**
- Added new validation in ngs mapping step, it compares biosheet and config.
- Corresponding unit tests were also included.
**Tests**
- No additional error/warning was observed in the automatic test.
- Local project worked as expected with changes to config file. Command called: `snappy-snake -S`
> Validate biosheet v. config

- snappy_pipeline/base.py
- snappy_pipeline/workflows/abstract/__init__.py
- snappy_pipeline/workflows/variant_combination/__init__.py
- snappy_pipeline/workflows/variant_filtration/__init__.py
- snappy_pipeline/workflows/variant_phasing/__init__.py
- snappy_pipeline/workflows/wgs_cnv_annotation/__init__.py
- snappy_pipeline/workflows/wgs_cnv_export/__init__.py
- snappy_pipeline/workflows/wgs_cnv_filtration/__init__.py
- snappy_pipeline/workflows/wgs_mei_calling/__init__.py
- snappy_pipeline/workflows/wgs_sv_annotation/__init__.py
- snappy_pipeline/workflows/wgs_sv_filtration/__init__.py
- snappy_wrappers/tools/fix_vcf.py
- tests/snappy_pipeline/test_base.py
addresses #6 
**Changes**
- Fixed Codacy warnings.
-  Implemented `UnknownFiltrationSourceException` and added it `CombineVariantsStepPartBase::_get_path()`.
- New unit test for `snappy_pipeline.base`.
> Fix codacy token issues

- snappy_pipeline/workflows/targeted_seq_cnv_calling/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_targeted_seq_cnv_calling.py
closes #60 
addresses #6  
**Changes**
- Added unit test for `targeted_seq_cnv_calling` workflow.
- Fixed Codacy issues.
> Fix Codacy issues in targeted_seq_cnv_calling

- snappy_pipeline/base.py
- snappy_pipeline/workflows/abstract/__init__.py
- tests/snappy_pipeline/test_base.py
- tests/snappy_pipeline/workflows/conftest.py
- tests/snappy_pipeline/workflows/test_workflows_abstract.py
- tests/snappy_pipeline/workflows/test_workflows_variant_calling.py
closes #48 
**Changes**
- New option to allow custom pedigree definitions in Germline sheets, i.e., based on specified field.
**Important:** It can only be merged after new `biomedsheet` release. Until then CI checks will fail.
> Join samples with the same family ID

- snappy_pipeline/chunk.py
- tests/snappy_pipeline/workflows/test_chunk.py
addresses #58 
**Changes**
* Added chunking history for incremental method - necessary to keep track of during snakemake call.
> Add chunk history

- snappy_wrappers/wrappers/gatk_hc_par/environment.yaml
- snappy_wrappers/wrappers/jannovar/environment.yaml
> Pin BCFTools version and related packages to 1.12

- snappy_wrappers/wrappers/eb_filter/wrapper.py
- snappy_wrappers/wrappers/mutect2/contamination/wrapper.py
- snappy_wrappers/wrappers/mutect2/filter/wrapper.py
- snappy_wrappers/wrappers/mutect2/pileup/wrapper.py
Hi @ericblanc20,
After you have done your changes on somatic-update branch, you can merge this on top of it and then we can merge the changes of both into main. Let me know if you need another review by then.
Cheers,
Clemens
> Fix mutect2 pileup wrapper. Fix log files for mutect2 steps.

- snappy_pipeline/workflows/wgs_sv_calling/__init__.py
- snappy_wrappers/wrappers/vcf_sv_filter/environment.yaml
closes #99 , closes #100 
**Changes**
*  Update wgs_sv_annotation wrapper requirements.
* Modified wgs_sv_calling workflow sample sheet filter: `_yield_result_files_dna_short()`
> Update WGS structural variants Workflow

- snappy_wrappers/wrappers/eb_filter_par/environment.yaml
- snappy_wrappers/wrappers/epitoper/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/combine_gvcf/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/discovery/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/genotyping/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/combine_gvcf/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/discovery/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/genotyping/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_par/environment.yaml
- snappy_wrappers/wrappers/gatk_phase_by_transmission/environment.yaml
- snappy_wrappers/wrappers/gatk_post_bam/environment.yaml
- snappy_wrappers/wrappers/gatk_read_backed_phasing/environment.yaml
- snappy_wrappers/wrappers/gatk_read_backed_phasing_par/environment.yaml
- snappy_wrappers/wrappers/gatk_ug_par/environment.yaml
- snappy_wrappers/wrappers/melt/environment.yaml
- snappy_wrappers/wrappers/minialign/run/environment.yaml
- snappy_wrappers/wrappers/mutect/environment.yaml
- snappy_wrappers/wrappers/mutect2/environment.yaml
**Changes**
* Updated CUBI conda url in environment files: cubi-conda.bihealth.org -> conda.cubi.bihealth.org
> Updated cubi conda url in environment files

- snappy_wrappers/wrappers/varfish_annotator/environment.yaml
> Updated varfish-annotator-cli version

- snappy_wrappers/wrappers/delly2/germline/environment.yaml
> Upgrade delly: v0.8.5 -> v1.0.3

- snappy_wrappers/wrappers/delly2/germline/merge_genotypes/wrapper.py
> WGS SV workflow: Delly step skips merge genotype if only one sample present

- snappy_pipeline/apps/impl/yaml_utils.py
- snappy_pipeline/apps/snappy_start_step.py
closes #149, closes #176
**Changes**
* Convert yaml content from StringIO to string
* Ignore empty lines in DEFAULT_CONFIG as yaml
> Fix snappy config update from `snappy-start-step` call

- snappy_pipeline/workflows/variant_checking/__init__.py
- snappy_wrappers/wrappers/peddy/run/environment.yaml
- tests/snappy_pipeline/workflows/test_workflows_variant_checking.py
closes #137, closes #138, closes #139 
**Test**
Germline WES - NA12878.
> Fix `peddy` call in for `variant_checking` workflow

- snappy_wrappers/wrappers/mutect2_par/run/parallel_mutect2.py
- tests/snappy_wrappers/wrappers/test_mutect2_par_run.py
> Expand mutect2 parallel tests to snakemake preamble

- snappy_pipeline/workflows/targeted_seq_cnv_annotation/__init__.py
- snappy_pipeline/workflows/targeted_seq_cnv_export/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_targeted_seq_cnv_annotation.py
- tests/snappy_pipeline/workflows/test_workflows_targeted_seq_cnv_export.py
> Remove XHMM config dependency from Targeted CNV annotation and export

- snappy_wrappers/wrappers/fastqc/environment.yaml
closes #145 
**Tests**
Germline WES - NA12878
Cancer WES (e2e)
> Update fastqc wrapper environment

- snappy_pipeline/apps/impl/yaml_utils.py
- tests/snappy_pipeline/apps/test_impl_yaml_utils.py
> Add 'OPTIONAL' as placeholder/tag for `DEFAULT_CONFIG`

- snappy_pipeline/workflows/somatic_variant_filtration/Snakefile
- snappy_pipeline/workflows/somatic_variant_filtration/__init__.py
- snappy_wrappers/wrappers/eb_filter/wrapper.py
- snappy_wrappers/wrappers/eb_filter_par/environment.yaml
- snappy_wrappers/wrappers/jannovar_par/annotate_somatic_vcf/parallel_annotate_somatic_vcf.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_variant_filtration.py
Fixes #120, fixes #144, fixes #148
> Fix `ebfilter` wrapper

- snappy_pipeline/workflows/somatic_gene_fusion_calling/Snakefile
- snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- snappy_wrappers/wrappers/arriba/environment.yaml
- snappy_wrappers/wrappers/arriba/run/environment.yaml
- snappy_wrappers/wrappers/arriba/run/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_gene_fusion_calling.py
> Added arriba to somatic_gene_fusion_calling step

- docs/index.rst
- docs/step/adapter_trimming.rst
- snappy_pipeline/workflows/adapter_trimming/__init__.py
> Include `adapter_trimming` documentation in Manual

- .github/workflows/ci.yml
- environment.yml
> CI: force 'py' re-installation via pip (#225)

- .github/workflows/ci.yml
> Pinned CI mamba to v0.27.0 (#230)

- snappy_pipeline/apps/tpls/pipeline_job.sh
Added custom logging directory as per [BIH HPC docs](https://hpc-docs.cubi.bihealth.org/slurm/snakemake/#custom-logging-directory)
> Add environment variable to redirect snake jobs output in slurm

- snappy_pipeline/workflows/ngs_mapping/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping_processed_fastq.py
> NGS Mapping: changed default for depth of coverage track (#239)

- snappy_wrappers/wrappers/varfish_annotator/annotate_sv/fix_manta_invs.py
**Changes**
* Fix bug introduced in #246
> Hotfix: bug in Manta inversion adjustment routine (#245)

- snappy_wrappers/wrappers/varfish_annotator/environment.yaml
Closes #251 
Wait until bioconda-recipes PR is done: https://github.com/bioconda/bioconda-recipes/pull/38117
> Bump varfish-annotator-cli to v0.28 (#251)

- snappy_pipeline/workflows/targeted_seq_cnv_export/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_targeted_seq_cnv_export.py
> Added missing argument to targeted_seq_cnv_export (#241)

- snappy_pipeline/workflows/wgs_cnv_annotation/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_wgs_cnv_annotation.py
> Remove ERDS reference affecting `wgs_cnv_annotation` (#257)

- snappy_pipeline/workflows/wgs_sv_annotation/__init__.py
- snappy_wrappers/wrappers/vcf_sv_filter/vcf_sv_filter.py
- tests/snappy_pipeline/workflows/test_workflows_wgs_sv_annotation.py
- tests/snappy_wrappers/wrappers/test_vcf_sv_filter.py
> Fixed issues with WGS SV Annotation (#258, #260)

- snappy_pipeline/workflows/adapter_trimming/__init__.py
- snappy_pipeline/workflows/gene_expression_quantification/__init__.py
- snappy_pipeline/workflows/hla_typing/__init__.py
- snappy_pipeline/workflows/ngs_data_qc/__init__.py
- snappy_pipeline/workflows/panel_of_normals/__init__.py
- snappy_pipeline/workflows/roh_calling/__init__.py
- snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- snappy_pipeline/workflows/somatic_msi_calling/__init__.py
- snappy_pipeline/workflows/somatic_purity_ploidy_estimate/__init__.py
- snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/__init__.py
- snappy_pipeline/workflows/somatic_variant_calling/__init__.py
- snappy_pipeline/workflows/somatic_wgs_cnv_calling/__init__.py
- snappy_pipeline/workflows/somatic_wgs_sv_calling/__init__.py
- snappy_pipeline/workflows/targeted_seq_cnv_calling/__init__.py
- snappy_pipeline/workflows/targeted_seq_mei_calling/__init__.py
- snappy_pipeline/workflows/variant_calling/__init__.py
- snappy_pipeline/workflows/variant_checking/__init__.py
- snappy_pipeline/workflows/wgs_mei_calling/__init__.py
- snappy_pipeline/workflows/wgs_sv_calling/__init__.py
> Tag field 'tools'  as required in workflows' default config (#249)

- snappy_pipeline/workflows/somatic_variant_annotation/Snakefile
- snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
- snappy_wrappers/wrappers/vep/environment.yaml
- snappy_wrappers/wrappers/vep/run/environment.yaml
- snappy_wrappers/wrappers/vep/run/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_variant_annotation.py
BREAKING CHANGE: most of the previous somatic variant annotation configuration is now put under the jannovar tool
> feat: added vep to the somatic variant annotation tools

- snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/__init__.py
- snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/cnvkit.rules
- snappy_pipeline/workflows/somatic_wgs_cnv_calling/__init__.py
- snappy_pipeline/workflows/somatic_wgs_cnv_calling/cnvkit.rules
- snappy_wrappers/wrappers/cnvkit/postprocess/environment.yaml
- snappy_wrappers/wrappers/cnvkit/postprocess/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_targeted_seq_cnv_calling.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_wgs_cnv_calling.py
Added an extra step `postprocess` to the `cnvkit` tool code: it merges the complete segment list and added the CNV calls with diploid as default. As usual, sex chromosomes are not handled properly.
Added an option to disable plots, this is because generation of some of them took forever.
> feat: Modification to cnvkit to enable cBioPortal import

- snappy_wrappers/wrappers/bbduk/environment.yaml
- snappy_wrappers/wrappers/bwa/wrapper.py
Fix 2 minor bugs that were around for some time...
> fix: fix trimadap-mt & bbduk java version

- snappy_pipeline/workflows/varfish_export/__init__.py
> fix: Always include alfred qc files in input for varfish export bam QC #511

- snappy_pipeline/workflows/somatic_variant_calling/model.py
Logic in the extra-args check was flipped.
> fix: extra args check

- snappy_pipeline/models/annotation.py
- snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
- snappy_wrappers/wrappers/vep/run/environment.yaml
> fix: replace vep/run wrapper environment.yaml with symlink to vep environment.yaml

- snappy_pipeline/workflows/varfish_export/__init__.py
- snappy_wrappers/wrappers/mehari/annotate_strucvars/wrapper.py
> fix: remove unnecessary inputs for annotate_strucvars (#592 )

- snappy_pipeline/workflows/cbioportal_export/model.py
- tests/snappy_pipeline/workflows/test_workflows_cbioportal_export.py
Update model to reflect changes in GenomeName.
> fix: update cbioportal model for study metadata

- snappy_pipeline/workflows/common/sv_calling.py
- snappy_pipeline/workflows/sv_calling_wgs/model.py
- tests/snappy_pipeline/workflows/test_workflows_sv_calling_wgs.py
Fixes to minor bug in the `sv_calling_wgs` step
> fix: germline sv calling tools not run (#626)
