- .github/workflows/ci.yml
- snappy_pipeline/workflows/abstract/__init__.py
- tests/snappy_pipeline/workflows/conftest.py
closes #13 
**Summary**
- Fixed bug while defining path to sample sheet (e.g., `2021_<project_name>.tsv`) before invalidating cache. Tests were modified accordingly. 
- Modified CI workflow configuration.
> Fix bug in cache invalidation - hope

- snappy_pipeline/apps/impl/fsmanip.py
- snappy_pipeline/apps/snappy_start_project.py
- snappy_pipeline/apps/snappy_start_step.py
- snappy_pipeline/apps/tpls/project_config.yaml
closes #44 
**Changes**
Now outputting changes to file only when adding or updating steps in the config. Example:
```
$ snappy-start-project --directory somatic_project
SNAPPY Pipeline -- start_project
================================
INFO: Creating directory somatic_project
INFO: Creating directory somatic_project/.snappy_pipeline
INFO: Creating project-wide configuration in somatic_project/.snappy_pipeline/config.yaml
INFO: Creating README file in in somatic_project/README.md
Do not forget to review .snappy_pipeline/config.yaml and to fill out README.md!
SUCCESS: All done, have a nice day!
```
> Decrease project start verbose

- snappy_wrappers/wrappers/eb_filter_par/environment.yaml
- snappy_wrappers/wrappers/epitoper/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/combine_gvcf/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/discovery/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf/genotyping/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/combine_gvcf/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/discovery/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_gvcf_par/genotyping/environment.yaml
- snappy_wrappers/wrappers/gatk_hc_par/environment.yaml
- snappy_wrappers/wrappers/gatk_phase_by_transmission/environment.yaml
- snappy_wrappers/wrappers/gatk_post_bam/environment.yaml
- snappy_wrappers/wrappers/gatk_read_backed_phasing/environment.yaml
- snappy_wrappers/wrappers/gatk_read_backed_phasing_par/environment.yaml
- snappy_wrappers/wrappers/gatk_ug_par/environment.yaml
- snappy_wrappers/wrappers/melt/environment.yaml
- snappy_wrappers/wrappers/minialign/run/environment.yaml
- snappy_wrappers/wrappers/mutect/environment.yaml
- snappy_wrappers/wrappers/mutect2/environment.yaml
- snappy_wrappers/wrappers/xhmm/environment_gatk.yaml
closes #68 
**Changes**
- Updated CUBI conda url to: cubi-conda.bihealth.org
> cubi conda url

- docs/overview.rst
- docs/quickstart.rst
- docs/usage.rst
Updated name change from cubi-snake to snappy-snake.
Added reference to README file, since no version of the pipeline is available while pip installing the file.
> snappy-snake name change

- snappy_pipeline/workflows/abstract/__init__.py
- tests/snappy_pipeline/workflows/conftest.py
- tests/snappy_pipeline/workflows/test_workflows_abstract.py
closes #79 
**Changes**
* Create symbolic link (i.e., 'link in') md5 files associated with fastq files as default behaviour.
> Link in MD5 rawdata files

- snappy_wrappers/wrappers/xhmm/merge_cov/wrapper.py
closes #86 
**Change**
Adjust XHMM merge cov rule to use depth list file instead of individual files as argument.
**Test**
Tested with a subset of NAMSE (11 samples). No difference between `master` and `86-fix-xhmm-argument` for file `bwa.xhmm_merge_cov.Agilent_SureSelect_Human_All_Exon_V6.RD.txt`.
> Adjust XHMM merge cov rule

- snappy_pipeline/workflows/wgs_cnv_annotation/__init__.py
- snappy_pipeline/workflows/wgs_cnv_calling/__init__.py
- snappy_pipeline/workflows/wgs_sv_annotation/__init__.py
closes #107, closes #108 
**Changes**
* Added requirements to default config for workflows:
- `wgs_cnv_annotation`
- `wgs_cnv_calling`
-  `wgs_sv_annotation`
* Removed `static_data` version reference in `wgs_cnv_calling` default config.
> Changed config requirements in CNV and SV workflows.

- environment.yml
- requirements/base.txt
- snappy_pipeline/workflows/cbioportal_export/Snakefile
- snappy_pipeline/workflows/cbioportal_export/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_cbioportal_export.py
addresses #110 
**Changes**
* Pinned varfish-cli version to avoid conflicts with biomedsheets.
* Adjusted `get_resouce()` use in `cbioportal_export` and created associated unit tests.
**Notes**
* Changes to requirements are unrelated to this PR but it won't be possible to see the tests results if they were not included ([commit](https://github.com/bihealth/snappy-pipeline/pull/127/commits/b44daa30ef46702c5a00b9f34733452fe53daae6)).
* I included several _"hope unit tests"_, i.e., tests for methods they should be implemented once we start refactoring the code.
* The code will not pass 'Checks', this PR is only about `cbioportal_export` tests - the others are been dealt with in the main feature branch.
> Ajust CBioPortal code - DRMAA removal

- .github/workflows/ci.yml
- environment.yml
- requirements/base.txt
- setup.py
- snappy_wrappers/wrappers/varfish_annotator/environment.yaml
closes #130, closes #132
**Changes**
* Updated `varfish-annotator-cli` to latest version in wrapper environment, v0.21.
* Drop support for Python v3.6, add support for v3.9.
* Changed channel priority during mamba package installation. Source: https://github.com/bioconda/bioconda-recipes/issues/34190
_Note:_ On the user level it required the following change to `.condarc`
```
$ cat .condarc
channel_priority: strict
channels:
- conda-forge
- bioconda
- defaults
```
> Adjust dependencies

- snappy_pipeline/workflows/variant_export/__init__.py
- snappy_wrappers/wrappers/varfish_annotator/annotate/wrapper.py
closes #113 
**Changes**
* Removed hardcoded genome release from `varfish_annotator/annotate`, get it from config instead.
**Tests**
For 11 samples from the NAMSE cohort compared the output from `master` vs. `113-variant-annotator-genome-release` branches (extensions: `.gts.tsv.gz`,  `db-infos.tsv.gz`, and `bam-qc.tsv.gz`). The outputted files are exactly the same.
> variant-annotator wrapper gets genome release from config

- snappy_wrappers/wrappers/freebayes/environment.yaml
- snappy_wrappers/wrappers/freebayes/wrapper.py
closes #135 
**Changes**
* Reintroduced conda-forge to env channels.
* Reintroduced hack to make `snappy-vcf_sort` available from wrapper env.
**Tests**
Tested using WES data for NA12878.
> Fix freebayes wrapper

- snappy_wrappers/wrappers/jannovar/annotate_somatic_vcf/wrapper.py
- snappy_wrappers/wrappers/jannovar/annotate_vcf/wrapper.py
- snappy_wrappers/wrappers/varfish_annotator/annotate/wrapper.py
- snappy_wrappers/wrappers/varfish_annotator/annotate_sv/wrapper.py
closes #182 
**Changes**
* Replaced Java VM garbage collection option: Concurrent Mark Sweep (CMS) -> G1 garbage collector
**Tests**
Cancer WES (e2e)
> Replace deprecated Java VM garbage collector option

- snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/Snakefile
- snappy_pipeline/workflows/somatic_targeted_seq_cnv_calling/__init__.py
- snappy_wrappers/wrappers/copywriter/prepare/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_targeted_seq_cnv_calling.py
> Fixed log path provided to step `prepare` from tool CopyWriter

- snappy_pipeline/workflows/ngs_mapping/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping.py
Small bug in the generation of log file names: the conda log files are required by the wrapper, but not created by the pipeline.
> Fixed log files path definitions for `GatkPostBamStepPart`

- snappy_pipeline/workflows/adapter_trimming/__init__.py
- snappy_pipeline/workflows/gene_expression_quantification/__init__.py
- snappy_pipeline/workflows/hla_typing/__init__.py
- snappy_pipeline/workflows/ngs_data_qc/__init__.py
- snappy_pipeline/workflows/ngs_mapping/__init__.py
- snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping_processed_fastq.py
addresses #214 
`ReadMappingStepPart._collect_reads()` will use the search path defined in `path_link_in`, but won't find the directories because it looks for directories as defined in the sample sheet ('P001'), not the library name('P001-N1-DNA1-WGS1'). Similar changes are required in all follow up workflows: `gene_expression_quantification`, `hla_typing`, etc...
```
DEBUG    file_crawler:find_file.py:138 Crawling "/preprocess" for dir_name "P001"
DEBUG    file_crawler:find_file.py:140   patterns in pattern set #0: ('*/*/*_R1.fastq.gz', '*/*/*_R2.fastq.gz')
DEBUG    file_crawler:find_file.py:140   patterns in pattern set #1: ('*/*/*_R1.fastq.gz.md5', '*/*/*_R2.fastq.gz.md5')
```
_Note:_ `test_workflows_ngs_mapping_processed_fastq.py` and `test_workflows_ngs_mapping.py` are basically the …
> More unit tests: workflows using FASTQ from preprocesed

- docs/index.rst
- docs/overview.rst
- docs/step/adapter_trimming.rst
- snappy_pipeline/apps/snappy_snake.py
- snappy_pipeline/workflows/abstract/__init__.py
- snappy_pipeline/workflows/adapter_trimming/Snakefile
- snappy_pipeline/workflows/adapter_trimming/__init__.py
- snappy_pipeline/workflows/gene_expression_quantification/__init__.py
- snappy_pipeline/workflows/hla_typing/__init__.py
- snappy_pipeline/workflows/ngs_data_qc/__init__.py
- snappy_pipeline/workflows/ngs_mapping/__init__.py
- snappy_pipeline/workflows/somatic_gene_fusion_calling/__init__.py
- snappy_wrappers/wrappers/bbduk/environment.yaml
- snappy_wrappers/wrappers/bbduk/run/environment.yaml
- snappy_wrappers/wrappers/bbduk/run/wrapper.py
- snappy_wrappers/wrappers/fastp/environment.yaml
- snappy_wrappers/wrappers/fastp/run/environment.yaml
- snappy_wrappers/wrappers/fastp/run/wrapper.py
- tests/snappy_pipeline/workflows/conftest.py
- tests/snappy_pipeline/workflows/test_workflows_abstract.py
- tests/snappy_pipeline/workflows/test_workflows_adapter_trimming.py
- tests/snappy_pipeline/workflows/test_workflows_cbioportal_export.py
- tests/snappy_pipeline/workflows/test_workflows_gene_expression_quantification_processed_fastq.py
- tests/snappy_pipeline/workflows/test_workflows_hla_typing_processed_fastq.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_data_qc_processed_fastq.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping_processed_fastq.py
closes #214 
**Important notes**
- the structure of the `output` directory is different from the other steps. The structure is `output/<tool>/<library>/out`. This is necessary as the step must produce `fastq` files that can be directly used by other steps (such as `ngs_mapping`).
- a `path_link_in` has been added to steps relying on `fastq` files for their input, through a modification of `LinkInPathGenerator`.
> Add adapter trimming workflow (214)

- snappy_wrappers/wrappers/bcftools/bcf_to_vcf/environment.yaml
> Bug fix: added missing env to wrapper bcf_to_vcf (#253)

- snappy_wrappers/wrappers/bcftools/call_joint/wrapper.py
- snappy_wrappers/wrappers/bcftools_call/wrapper.py
- snappy_wrappers/wrappers/gatk3_hc/wrapper.py
- snappy_wrappers/wrappers/gatk3_ug/wrapper.py
- snappy_wrappers/wrappers/gatk4_hc/combine_gvcfs/wrapper.py
- snappy_wrappers/wrappers/gatk4_hc/discover/wrapper.py
- snappy_wrappers/wrappers/gatk4_hc/genotype/wrapper.py
- snappy_wrappers/wrappers/gatk4_hc/joint/wrapper.py
- snappy_wrappers/wrappers/varscan/call_joint/wrapper.py
This actually overrides TMPDIR in the called bash functions.
> revert: not using parallel --workdir (#328)

- snappy_pipeline/apps/snappy_snake.py
- snappy_pipeline/workflows/variant_export_external/__init__.py
- snappy_wrappers/wrappers/varfish_annotator/annotate/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_variant_export_external.py
re-enable wgs_cnv_export_external:
- the 'wgs_cnv_export_external' was removed from the snappy_snake app by accident. I has now been re-added
solve issues with variant_export_external:
- changes in the wrapper for varfish_annotator broke the 'variant_export_external' step, since it also relies on this. The expected log files and output links/files have been updated.
> fix: solve issues with variant_export_external and re-enable wgs_cnv_export_external

- snappy_wrappers/wrappers/gcnv/contig_ploidy_case_mode/wrapper.py
In particular for Agilent V8, the ploidy calls were very unreliable. We need to hard-fix this in the ploidy calling to get results at all. Complementary methods must be used for checking ploidy sanity.
> fix: enforce ploidy in GATK gCNV ploidy calling wrapper

- snappy_pipeline/workflows/varfish_export/__init__.py
The code previously erroneously required consistent library kits.
> fix: fixing problem in running varfish-export

- snappy_pipeline/workflows/varfish_export/__init__.py
- snappy_pipeline/workflows/variant_export_external/__init__.py
- snappy_pipeline/workflows/wgs_cnv_export_external/__init__.py
- snappy_pipeline/workflows/wgs_sv_export_external/__init__.py
- snappy_wrappers/wrappers/varfish_annotator/annotate/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_varfish_export.py
- tests/snappy_pipeline/workflows/test_workflows_variant_export_external.py
- tests/snappy_pipeline/workflows/test_workflows_wgs_cnv_export_external.py
- tests/snappy_pipeline/workflows/test_workflows_wgs_sv_export_external.py
Previously, the BED file value was always used for WGS data and never used for WES data.  Now, it is used when it has been provided (not the empty string and not null/None).
CC @xiamaz
> feat: path_exon_bed can be provided independent of data type (#389)

- requirements/base.txt
This fixes #396, as snakemake versions between `7.20` and `7.24.0` introduced a bug that caused python version detection to crash on any version without f-strings (which were introduced in py36).
This also adds an upper limit on the last known-working snakemake version, which should only be manually incremented.
> fix: update snakemake version requirements

- docs/dev_intro.rst
This adds a small warning to the pipeline step docs regarding naming conventions in the workflow `Snakefile`.
Needed for https://github.com/bihealth/cubi-tk/pull/174
> docs: add warning for writing new workflow steps

- snappy_pipeline/workflows/cbioportal_export/__init__.py
- snappy_pipeline/workflows/somatic_variant_annotation/Snakefile
- snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
- snappy_wrappers/wrappers/cbioportal/merge_tables/script.R
- snappy_wrappers/wrappers/jannovar/annotate_somatic_vcf/wrapper.py
- snappy_wrappers/wrappers/vcf2maf/vcf_to_table/jannovar.yaml
- snappy_wrappers/wrappers/vcf2maf/vcf_to_table/protein_mutation_parser.py
- snappy_wrappers/wrappers/vcf2maf/vcf_to_table/vep.yaml
- snappy_wrappers/wrappers/vep/post_filter/wrapper.py
- snappy_wrappers/wrappers/vep/run/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_cbioportal_export.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_variant_annotation.py
Impose user-defined annotation order for VEP.
Previously, the wrapper was using the default order, based on ENSEMBL canonical transcript.
Because of that choice, many variant were not uploaded to cBioPortal.
The default choice now prioritizes protein-coding genes with MANE transcripts.
Many variants are now recovered in cBioPortal views.
> feat: 438 vep annotation order

- snappy_wrappers/wrappers/mehari/annotate_strucvars/wrapper.py
> fix: Fixing feature-effects compression

- snappy_wrappers/wrappers/gcnv/environment.yaml
fix: definition of gcnv conda enviroment for mamba>=1.3 (#452)
Leaving out the 'default::' seems to work, see my comment on the issue
> fix: definition of gcnv conda enviroment for mamba>=1.3 (#452)

- snappy_wrappers/wrappers/gcnv/call_cnvs_case_mode/wrapper.py
- snappy_wrappers/wrappers/gcnv/contig_ploidy_case_mode/wrapper.py
Some of the gcnv step_parts and their associated wrappers create collections of output folders that are currently not tracked by snakemake. Additionally gcnv does only partially overwrite these output files & folders, especially if it is run with fewer samples than in a previous run.
This changes the case_mode wrappers for contig_ploidy and call_cnvs step-parts to always remove the directories they will write into to ensure all output files belong to the current snappy run.
This could be extended to the cohort_mode wrappers, however they might be used in cases where removal of previous samples is not intended, since they could still be relevant (whereas in case mode this is not the case).
Fixes #443
> fix: gcnv contig wrapper scripts do not clean their output folders (#443)

- snappy_pipeline/workflows/ngs_data_qc/__init__.py
- snappy_pipeline/workflows/ngs_mapping/Snakefile
- snappy_pipeline/workflows/ngs_mapping/__init__.py
- snappy_wrappers/wrapper_parallel.py
- snappy_wrappers/wrappers/cbioportal/generate_cna/script.R
- snappy_wrappers/wrappers/cbioportal/merge_tables/script.R
- snappy_wrappers/wrappers/cnvkit/postprocess/wrapper.py
- snappy_wrappers/wrappers/mbcs/environment.yaml
- snappy_wrappers/wrappers/mbcs/wrapper.py
- snappy_wrappers/wrappers/mutect2_par/prepare_panel/parallel_prepare_panel.py
- snappy_wrappers/wrappers/picard/prepare/wrapper.py
- snappy_wrappers/wrappers/purecn/run/wrapper.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_data_qc_processed_fastq.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping.py
- tests/snappy_pipeline/workflows/test_workflows_ngs_mapping_processed_fastq.py
- tests/snappy_wrappers/wrappers/data/mutect2_par_prepare_panel.snakemake
- tests/snappy_wrappers/wrappers/test_mutect2_par_prepare_panel.py
The MBCs are typically used on FFPE data, where library complexity may be low. These data are also often compromised by FFPE or oxo-G artifacts which require careful analysis & filtration of somatic variants. Base-quality re-calibration (BQSR) should be used in these cases.
The implementation has 5 steps:
1. Trimming the MBC sequence at the read's 5' end and inserting it in the read name for further processing.
2. Mapping the reads
3. Merging separate libraries
4. Marking the duplicates using the information in read names
5. Performing BQSR
Steps 1 & 2 must be done separately on separate libraries, in order to easily insert read groups information requires by BQSR. The separate bam files must be merged before marking duplicates.
Because of the multiple operations required to produce the …
> feat: Initial implementation of Molecular bar codes handling using AGeNT

- snappy_wrappers/wrappers/mutect2/environment.yaml
The mutect2/filter wrapper requires the gawk version of `match(…)`, so this PR explicitly requires gawk in the conda environment.
> fix: explicitly require gawk in mutect2/filter wrapper environment

- snappy_pipeline/workflows/somatic_variant_filtration/__init__.py
Some filter rules in the somatic_variant_filtration workflow were missing checks for `has_annotation` to construct the correct input/output/log paths. This PR fixes that.
> fix: missing check for `has_annotation` in somatic_variant_filtration rules

- .tests/test-workflow/config/cancer_wes/config.yaml.jinja2
- docs/step_generic.rst
- snappy_pipeline/workflows/abstract/__init__.py
- snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
- snappy_pipeline/workflows/somatic_variant_calling/__init__.py
- snappy_pipeline/workflows/somatic_variant_filtration/Snakefile
- snappy_pipeline/workflows/somatic_variant_filtration/__init__.py
- snappy_wrappers/wrappers/bcftools/filter/wrapper.py
- snappy_wrappers/wrappers/bcftools/protected/wrapper.py
- snappy_wrappers/wrappers/bcftools/regions/wrapper.py
- snappy_wrappers/wrappers/eb_filter/wrapper.py
- snappy_wrappers/wrappers/mutect2/run/wrapper.py
- tests/snappy_pipeline/workflows/conftest.py
- tests/snappy_pipeline/workflows/test_workflows_somatic_variant_filtration.py
This is a first attempt to support tumor-only samples in the somatic snappy branch.
Many points are still open for discussion/criticism:
1. The changes are limited to SNVs & indels, I haven't looked at changes required for CNVs (exome nor wgs).
2. The (theoretical) possibility of joint calling multiple tumor samples from a single donor has been removed. I am not sure that it ever worked.
3. The extraction type is now mandatory, and samples without one will not be processed. Samples sequenced with long reads may also be rejected.
4. The tests don't exercise samples without normals, so coverage will decrease.
The proposed overhaul/replacement of biomedsheets should alter how the samples are connected to each others. So points 2 & 3 (and possibly 4 too) may be revisited when we have a plan …
> feat: support for somatic variant calling without normal

- snappy_wrappers/wrappers/bcftools/TMB/wrapper.py
When the user's locale was set to one that uses `,` instead of `.` as a decimal point, the wrapper would fail.
> fix: set locale to C in bcftools/TMB wrapper

- snappy_wrappers/wrappers/gcnv/call_cnvs_case_mode/wrapper.py
- snappy_wrappers/wrappers/gcnv/call_cnvs_cohort_mode/wrapper.py
- snappy_wrappers/wrappers/gcnv/contig_ploidy/wrapper.py
- snappy_wrappers/wrappers/gcnv/contig_ploidy_case_mode/wrapper.py
- snappy_wrappers/wrappers/gcnv/environment.yaml
- snappy_wrappers/wrappers/gcnv/post_germline_calls/wrapper.py
- snappy_wrappers/wrappers/gcnv/post_germline_calls_case_mode/wrapper.py
- snappy_wrappers/wrappers/gcnv/preprocess_intervals/wrapper.py
gcnvkernel 0.8 is not installable from conda-forge (only), since some dependencies are only available from anaconda.
We therefore update to gcnvkernel 0.9, which has updated its dependencies, and use the opportunity to update GATK to version 4.6 as well.
> feat: Update GCNV environment to 0.9 kernel and GATK4.6.1

- pyproject.toml
- uv.lock
Accidentally, the pyproject.toml did not restrict to `snakemake < 8`. While at it, also add upper limits for other dependencies and update the uv.lock accordingly.
> chore: fix dependency version constraints

- snappy_pipeline/workflows/somatic_variant_filtration/model.py
Please check wether parameter types are consistent with EBFilter.
> fix: change type of parameters to adhere to specification of EBFilter

- pyproject.toml
- uv.lock
For now, restrict pydantic to 2.9 because of the change in behaviour regarding type aliases.
> fix: restrict pydantic to 2.9.x
